name: Deploy

on: push
env:
    ITCH_USERNAME: chowieuk
    ITCH_GAME_ID: amomo
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy to Itch.io
        strategy:
            fail-fast: true
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Archive build
              run: git archive --format=zip --output ./build.zip master
            - name: Upload to Itch
              uses: manleydev/butler-publish-itchio-action@master
              env:
                  BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
                  CHANNEL: HTML
                  ITCH_GAME: amomo
                  ITCH_USER: chowieuk
                  PACKAGE: ./build.zip
